version: "3.8"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQLDB_HOST = localhost

      - MYSQLDB_USER=root
      - MYSQLDB_PASSWORD=password
      - MYSQLDB_DATABASE=projecto_arquisoft
      - MYSQLDB_LOCAL_PORT=3306
      - MYSQLDB_DOCKER_PORT=3307
      - MYSQLDB_ROOT_PASSWORD= MYSQL_ALLOW_EMPTY_PASSWORD=1

      - NODE_LOCAL_PORT=6868
      - NODE_DOCKER_PORT=8080
